### ISSUE TITLE
为什么不能获取twitter账号id自动建立一个对应的账号

### ISSUE THREAD

**Issue by maggch97** [TechLeadMall/PornKiller#2]
现在这个账号注册和登录页面还不能被chrome的密码管理器记住

**Comment by TechLeadMall** [comment]
确实可以，但是创建了账户还得做个管理系统的账户映射，如果完全把管理系统改造成基于twitter账户ID，就不需要映射了，但是登录会不稳定，而且推特ID是公开的，不安全。
另外的考虑是因为少部分人对于隐私问题是敏感的，目前的设计，不需要推特ID，也不传账户使用者的推特ID到服务器。

**Comment by maggch97** [comment]
我明白你的意思, 要解决伪造id的问题

这个就必须要引入服务端得验证,本地无论验证什么最后都能被伪造

上传cookie到服务器, 服务器负责调用twitter某个userinfo的api验证, 但是有人会有隐私顾虑

**Comment by maggch97** [comment]
https://developer.twitter.com/zh-cn/docs/authentication/overview twitter有oauth，直接用oauth验证就可以

**Comment by TechLeadMall** [comment]
没看到这个消息，用户对隐私比较在意，所以我觉得用oauth不太合适
